

export const SQUARE_CLICKED = "SQUARE_CLICKED";
export const IS_THERE_WINNER = "IS_THERE_WINNER";
export const HANDLE_RESTART = "HANDLE_RESTART";
export const HIGHlIGHT_WINNING_SQUARES = "HIGHlIGHT_WINNING_SQUARES";
export const CHANGE_TURN = "CHANGE_TURN";